version: "3.6"

services:
  development_default: &DEVELOPMENT_DEFAULT
    build:
      context: .
      target: development
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - GOOGLE_CLIENT_ID=none
      - GOOGLE_CLIENT_SECRET=none

  web:
    <<: *DEVELOPMENT_DEFAULT
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: ./scripts/load_db.sh flask run --host=0.0.0.0

  worker:
    <<: *DEVELOPMENT_DEFAULT
    depends_on:
      - db

  db:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=jahvon
      - POSTGRES_PASSWORD=jahvon