"""empty message

Revision ID: 0d7d1545a127
Revises: 771caf5fbd7e
Create Date: 2019-01-06 01:31:48.091644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7d1545a127'
down_revision = '771caf5fbd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'tokens')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tokens', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('users', 'username')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
